### ISSUE TITLE
PSA: You do NOT need this plugin

### ISSUE THREAD

**Issue by marlonrichert** [mafredri/zsh-async#64] opened 2023-04-06 12:25 UTC
You can create any number of asynchronous processes in Zsh simply by using a [file descriptor](https://zsh.sourceforge.io/Doc/Release/Redirection.html#Opening-file-descriptors-using-parameters) and [process substitution](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Process-Substitution):

```sh
typeset -i fd=-1
exec {fd}< <( ... )
```

You can then later read the output from the file descriptor (FD) this creates. For example, you can [redirect](https://zsh.sourceforge.io/Doc/Release/Redirection.html#Redirection) your FD's output straight to your terminal:

```sh
<&$fd
```

or use [`read`](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#index-read) to capture the output in a variable for further processing:

```sh
local REPLY=''
read -ru $fd
```

Both of these will wait for input to be available and finish when the process behind the file descriptor is done.

Alternatively, if you want to process the output immediately as it becomes available, use the [Zsh Line Editor (ZLE)](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#index-zle) to connect a handler widget to the FD and process the output there:

```sh
zle -Fw "$fd" widget
zle -N widget handler-function

handler-function() {
  local -i fd=$1
  zle -F $fd  # Unhook immediately, to avoid getting called more than once.
  ...
}
```

In any case, wrap your processing code in an [`always` block](https://zsh.sourceforge.io/Doc/Release/Shell-Grammar.html#index-always) to make sure you close the FD when you're done:
```sh
{
  ...
} always {
  exec {fd}<&-
}
```

This all is much more efficient than using this plugin, which uses a [pseudoterminal](https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#The-zsh_002fzpty-Module) to asynchronously run your code in an interactive shell.

**Comment by mafredri** [comment] 2023-04-06 15:29
While I appreciate you sharing knowledge, I would've appreciated a slightly less aggressive take. This style of writing is suitable elsewhere, but on the projects own issue tracker? It does feel like you have a personal vendetta with this project.

Anyway, this issue does ignore a bunch of features that are part of this library, like timing commands, separating stdout/stderr, canceling in-progress work and ability to know when commands complete (even without zle watcher), etc. Obviously most of that can be implemented with this method, yet at some point you may have `zsh-async2`.

I have considered creating backends for this project, e.g. `zpty` and `subshell`, where the latter would use the method you wrote about. Haven't gotten around to it though.

Closing as a duplicate of #24.

**Closed as completed by mafredri** 2023-04-06 15:29 UTC

**Comment by marlonrichert** [comment] 2023-04-26 12:53
You are right, I worded that too aggressively. My apologies.
